LoadModule dav_module modules/mod_dav.so
LoadModule dav_fs_module modules/mod_dav_fs.so
LoadModule auth_basic_module modules/mod_auth_basic.so
LoadModule authn_file_module modules/mod_authn_file.so
LoadModule authz_user_module modules/mod_authz_user.so

DavLockDB /tmp/DavLock

Listen 8080
<VirtualHost *:8080>
    DocumentRoot /data/webdav
    <Directory /data/webdav>
        Dav On
        AuthType Basic
        AuthName "WebDAV"
        AuthUserFile /etc/apache2/webdav.htpasswd
        Require valid-user
        Options Indexes
    </Directory>
</VirtualHost>
